# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhereIsMyFood-Driver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhereIsMyFood-Driver
  pod 'LGSideMenuController'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SinchVerification-Swift'
  pod 'CountryPickerSwift'
  pod 'SkyFloatingLabelTextField', '~> 3.0’
end
